# default.yaml
pretrained_model_name_or_path: "weights/stable-diffusion-v1-5"
brushnet_model_name_or_path: "weights/diffuEraser"
revision: null
variant: null
tokenizer_name: null
output_dir: "brushnet-model"
cache_dir: null
seed: 114514
resolution: 512
num_frames: 22  
train_batch_size: 1
num_train_epochs: 10
max_train_steps: 10000
checkpointing_steps: 500
checkpoints_total_limit: 5
resume_from_checkpoint: null
gradient_accumulation_steps: 2  
gradient_checkpointing: True  
learning_rate: 5e-6
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: True  
dataloader_num_workers: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
logging_dir: "logs"
allow_tf32: false
report_to: "tensorboard"
mixed_precision: "fp16"  
enable_xformers_memory_efficient_attention: false
set_grads_to_none: false
dataset_name: null
dataset_config_name: null
train_data_dir: "VideoSelection" 
mask_data_dir: "MaskSelection"
max_train_samples: 10000
proportion_empty_prompts: 0
tracker_project_name: "train_Unet_brushnet"
vae_path: "weights/sd-vae-ft-mse"
